services:
  dbt:
    build: .
    container_name: dbt_crm
    volumes:
      - .:/usr/app
    working_dir: /usr/app
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=crm_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    entrypoint: ["tail", "-f", "/dev/null"]

  airflow-webserver:
    image: apache/airflow:3.0.0
    restart: always
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@host.docker.internal:5432/airflow
      - AIRFLOW__CORE__FERNET_KEY=''
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=true
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__API__AUTH_BACKENDS='airflow.api.auth.backend.basic_auth'
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=crm_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./dbt:/opt/airflow/dbt
      - ./logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:3.0.0
    restart: always
    depends_on:
      - airflow-webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@host.docker.internal:5432/airflow
      - AIRFLOW__CORE__FERNET_KEY=''
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=true
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=crm_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./dbt:/opt/airflow/dbt
      - ./logs:/opt/airflow/logs
    command: scheduler
